In [1]:
from neuralnet import NeuralNetMLP
import numpy as np
import matplotlib.pyplot as plt

In [2]:
nn = NeuralNetMLP(n_hidden=100,
                   l2=0.01,
                   epochs=300,
                   eta=0.0005,
                   minibatch_size=100,
                   shuffle=True, seed=1)

In [3]:
dataset = np.load('dataset/mnist_scaled.npz')
X_train, y_train, X_test, y_test = [dataset[f] for f in ['X_train', 'y_train', 'X_test', 'y_test']]

In [4]:
nn.fit(X_train=X_train[:55000], 
       y_train=y_train[:55000],
       X_valid=X_train[55000:],
       y_valid=y_train[55000:])

300/300 | Cost: 4134.36 | Train/Valid Acc.: 99.57%/98.02%  

In [5]:
nn

In [6]:
nn.predict(X_test, y_test)

TypeError: predict() takes 2 positional arguments but 3 were given

In [7]:
nn.predict(X_test)

array([7, 2, 1, ..., 4, 5, 6])

In [8]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [9]:
X_test

array([[-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       ...,
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.]])

In [10]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [11]:
nn.predict(y_test)

ValueError: shapes (10000,) and (784,100) not aligned: 10000 (dim 0) != 784 (dim 0)

In [12]:
nn.predict(X_test)

array([7, 2, 1, ..., 4, 5, 6])

In [1]:
nn.predict(X_test)

NameError: name 'nn' is not defined